programming5
SerhiyToroniy/PythonTasks pull request #11
Opened 2020-10-15 11:53 UTC by SerhiyToroniy

2020-10-21 20:17 UTC, tetianastoyko requested changes

2020-10-21 20:17 UTC, tetianastoyko commented on Collection.py
>  from decimal import Decimal
Рядки 17-24 і 87-95 - окремий приватний метод і цикл
повторюються

2020-10-21 20:17 UTC, tetianastoyko commented on Collection.py
>                  if i.upper().find("AMOUNT")!= -1:    lst[j] = str(round(Decimal(float(lst[j])),2))
if i[0]+i[1]!="ge" and i[0]+i[1]!="se" and i[0]+i[1]!="__":
я вже за це писаала, це тричі зустрічається, для чого це?

2020-10-21 20:17 UTC, tetianastoyko commented on Collection.py
>                  if i.upper().find("AMOUNT")!= -1:    lst[j] = str(round(Decimal(float(lst[j])),2))
вже і 4 раз знайшла
що за незрозуміле порівняння? Думаю, що без потреби

2020-10-21 20:17 UTC, tetianastoyko commented on Collection.py
меню в колекції??????
винести і на кожен пункт меню - окремий метод

2020-10-21 20:17 UTC, tetianastoyko commented on Collection.py
> -        if not Validation().digit_check(obj.getAMOUNT()) or not Validation().low_up_limit_check(obj.getAMOUNT(), -1):   raise TypeError
Мають бути валідатоди - декоратори, використані в класі SwiftTransfer

2020-10-21 20:17 UTC, tetianastoyko commented on Collection.py
>  def validate_obj(obj):
цього методу взагалі не має бути

2020-10-21 20:17 UTC, tetianastoyko commented on Collection.py
> +def validate_lst(lst): #the main validation function
цього методу взагалі не має бути

2020-10-21 20:17 UTC, tetianastoyko commented on Collection.py
>  from SwiftTransfer import * #import class SwiftTransfer
не бачу класу SwiftTransfer в PR

2020-10-22 07:07 UTC, SerhiyToroniy commented on Collection.py
>                  if i.upper().find("AMOUNT")!= -1:    lst[j] = str(round(Decimal(float(lst[j])),2))
> вже і 4 раз знайшла
> що за незрозуміле порівняння? Думаю, що без потреби

це для того щоб пропускати гетери й сетери і магічні методи в циклі

2021-02-22 20:10 UTC, closed without merging